name: Report
on:
  workflow_run:
    workflows: [Github-CI]
    types: [completed]

permissions:
  checks: write

jobs:
  testpackage_report_ukkoGPU:
    runs-on: ubuntu-latest
    steps:
      - name: download testpackage output
        # Note we are downloading an artifact from a
        # *different* workflow here.
        uses: ursg/action-download-artifact@v2
        with:
          name: testpackage-output-ukkoGPU
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: unpack and process pr output
        id: unpack
        run: |
          tar -xzvf testpackage-output-ukkoGPU.tar.gz
          cat testpackage_output_variables.txt >> $GITHUB_OUTPUT
          # Limit Report filesize, as github only allows 64k PR reports
          truncate --size='<60K' testpackage_check_description.txt
      - name: Generate PR check report
        uses: ursg/checks-action@v1.6.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{github.event.workflow_run.head_sha}}
          name: Testpackage Ukko-GPU result
          conclusion: ${{ steps.unpack.outputs.conclusion }}
          output: |
            {"title": "Testpackage Ukko-GPU result", "summary":"${{ steps.unpack.outputs.summary }}"}
          output_text_description_file: testpackage_check_description.txt
